### ISSUE TITLE
[QUESTION] Elasticsearch feeding

### ISSUE THREAD

**Issue by wcypierre** [twintproject/twint#150]
>Make sure you've checked the following:
- [Y] Python version is 3.5 or higher.
- [Y] Using the latest version of Twint.
- [Y] I have searched the issues and there are no duplicates of this issue/question/request.

### Description of Issue
I've been trying to get the dashboard working but can't seem to get it working in the creating index step in https://github.com/haccer/twint/wiki/Elasticsearch
I ran "python3 Twint.py -es 192.168.88.17:9200 -u inter --since 2018-06-09" and I've been getting this error
![twint](https://user-images.githubusercontent.com/1132980/41201803-bff9aecc-6cf1-11e8-84f9-3db6ca0b6e5a.png)

Tried passing a random essid and the sync went through but got stuck on the next step when I copy paste index-tweets.json on the Dev Tools and got resource_already_exists_exception
![index already exists](https://user-images.githubusercontent.com/1132980/41201835-26050996-6cf2-11e8-822c-00680f0b0cee.png)

Any clue on what went wrong on my steps?

### Environment Details
OS: Ubuntu 18.04
Python: 3.6.5
Elasticsearch Version: 6.2.4
Twint: pulled latest from master branch

**Comment by wcypierre** [comment]
This is what I get in the twint index if I pass the custom essid

```
{
  "twint": {
    "aliases": {},
    "mappings": {
      "items": {
        "properties": {
          "date": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "day": {
            "type": "long"
          },
          "essid": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "hour": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "id": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "likes": {
            "type": "boolean"
          },
          "link": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "location": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "replies": {
            "type": "boolean"
          },
          "retweets": {
            "type": "boolean"
          },
          "timezone": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "tweet": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "user_id": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "user_rt": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "username": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          }
        }
      }
    },
    "settings": {
      "index": {
        "creation_date": "1528635034991",
        "number_of_shards": "5",
        "number_of_replicas": "1",
        "uuid": "QGha27oFSyWrzj-WyzD4cA",
        "version": {
          "created": "6020499"
        },
        "provided_name": "twint"
      }
    }
  }
}
```

**Comment by pielco11** [comment]
The issue that you see in `DevTools` is because an index with that name already exists, to delete an index run `DELETE *index-name*` where `*index-name*` is the name of the index that you want to delete

**Comment by wcypierre** [comment]
What value should I put in config.Essid?

**Comment by wcypierre** [comment]
I have tried that as well. I've deleted the Twint index, did step 2 first (which is to create the index twint first from the index-tweets.json file) and then run step 1 but to no avail

**Comment by pielco11** [comment]
For `config.Essid` choose whatever you prefer, letters and/or numbers

Can you elaborate a bit on what you did, please?

**Comment by wcypierre** [comment]
In short, I've done the two steps here in different ordering but I don't see the output that I'm supposed to see in https://github.com/haccer/twint/wiki/Elasticsearch

A. Let Twint generate the index (original step in the wiki)
Ran "python3 Twint.py -es 192.168.88.17:9200 -u inter --since 2018-06-09" and it generated the twint index, however in Create Index Pattern, I can't see any dropdown value for the Time filter (supposedly so due to the _Date_ is of _text_ type instead of _date_ type compared to the one in index-tweets.json
![image](https://user-images.githubusercontent.com/1132980/41202217-5af562a8-6cf8-11e8-8203-8a5e5659699c.png)

I do see values in Discover but it is not as what is in the wiki 

B. Pre-create the Twint index using index-tweets.json
Ran "python3 Twint.py -es 192.168.88.17:9200 -u inter --since 2018-06-09" and I can generate the index and see the _Date_ value in the Time filter dropdown but I see nothing in Discover

**Comment by pielco11** [comment]
Very clear, will look at it asap

**Comment by wcypierre** [comment]
I am guessing it is because of the metadata difference between the one in _index-tweets.json_ and the one that is generated by twint https://github.com/haccer/twint/issues/150#issuecomment-396048137
but I'm new to elasticsearch so I'm not sure of how it works in terms of data mapping to the schema

**Comment by pielco11** [comment]
Hi,

thanks for waiting.
So the main issue is that Elasticsearch creates a new index if it does not find the index which you are indexing to, and that index differs a bit from what I chose (mine is not a rule, just what I'm suggesting).

You can create new indexes as explained in the Wiki and changing the index name (`PUT customindex ...`) **before** indexing with Twint with the new `customindex` index.
I'll edit the code so that this step will be automated.

You can also index **before** creating the index in Elasticsearch, but that you'll have to run `DELETE customindex` in `DevTools`, than `PUT customindex ...`, and after that update the index pattern

![screenshot_19](https://user-images.githubusercontent.com/17363750/41428917-c88faccc-700b-11e8-9730-5f86ce521177.png)

PS: now `config.Essid` can be `None`

**Comment by pielco11** [comment]
Closing since I don't get the error again, in case feel free to reopen and/or comment

**Comment by pielco11** [comment]
Hello @alannaparker45 ,

did you choose the time field before creating the index? [Here](https://logz.io/wp-content/uploads/2017/07/configure-kibana-index-pattern.png) an example on what you should see, not related to twint.

**Comment by pielco11** [comment]
@alannaparker45 that was a typo and now it's fixed

![immagine](https://user-images.githubusercontent.com/17363750/49377810-640bdc80-f70b-11e8-8f64-2f2b14fa75f2.png)

![immagine](https://user-images.githubusercontent.com/17363750/49377866-8a317c80-f70b-11e8-9651-97e040dae3ec.png)

![immagine](https://user-images.githubusercontent.com/17363750/49377919-adf4c280-f70b-11e8-8252-895ee7592556.png)

![immagine](https://user-images.githubusercontent.com/17363750/49377960-c664dd00-f70b-11e8-9a5c-aa3592f8ad7a.png)

**Comment by pielco11** [comment]
Please note that **twintuser** index is created as well because Twint scrapes also the informations of the "target user", the one that you specify with `-u/--username` argument

**Comment by alannaparker45** [comment]
@pielco11 thanks,
I'd fixed the first issue related to the typo geo_point, but it still not working, i cannot find the file to edit this part of code where the "someindex3" is located.
![49377810-640bdc80-f70b-11e8-8f64-2f2b14fa75f2](https://user-images.githubusercontent.com/45429997/49381822-1d22e480-f715-11e8-8111-1be691889426.png)

**Comment by pielco11** [comment]
@alannaparker45 that is just a script that I wrote to do some testing

I suggest you to go to `Dev Tools` panel and delete old indexes, then re-run the code that you were trying to play with

![immagine](https://user-images.githubusercontent.com/17363750/49382180-07fa8580-f716-11e8-9a0f-6f530d5f4ec7.png)

![immagine](https://user-images.githubusercontent.com/17363750/49382209-1cd71900-f716-11e8-9341-d5fae3382696.png)

So for example, if you were trying to scrape tweets tweeted by google, now you have to run a code similar to this:

```python
import twint

c = twint.Config()
c.Username = "google"
c.Elasticsearch = "localhost:9200"

twint.run.Search(c)
```

**Comment by alannaparker45** [comment]
Thanks for your fast response. Yesterday I unistalled and installed again Kibana and Elastic, just in case that something was wrong with the code. When I tried to make a new Index, I had the same problem. Before I tried to create a new index, I changed geopoint into geo_point.

**Comment by pielco11** [comment]
@alannaparker45 so I guess that with the new setup and fix everything is working fine, if not just say

**Comment by alannaparker45** [comment]
The option of the Index are the same of the other day and in the Index "twinttweets" there aren't any options. It must appear "date" or "timestamp" isn't it?
![imagen](https://user-images.githubusercontent.com/45429997/49430617-cf0cf000-f7ab-11e8-91e9-ada3b8725978.png)
![imagen](https://user-images.githubusercontent.com/45429997/49430851-5c504480-f7ac-11e8-8393-7bd4f6b93fd7.png)

**Comment by pielco11** [comment]
@alannaparker45 the first screenshot is about the index for users, `twintuser`, the second one is the index for tweets, `twinttweets`, and in your case it seems that this index does not have a date/time field

So now that you have to do is:

### Delete the tweets index

![immagine](https://user-images.githubusercontent.com/17363750/49433247-d9ca8380-f7b1-11e8-9db1-ce5aa04480ac.png)

### Delete the user index

![immagine](https://user-images.githubusercontent.com/17363750/49433367-24e49680-f7b2-11e8-8f3c-5cc2fae56539.png)

### Create a new one by indexing some tweets 

![immagine](https://user-images.githubusercontent.com/17363750/49433669-d4216d80-f7b2-11e8-9b14-5a4fbc0c991d.png)

Here `t.py` is just a script that I wrote, what it does is just indexing some tweets of an account. This script is custom and not provided in the Twint repo, it's just an example.

### Create the index pattern for tweets

![immagine](https://user-images.githubusercontent.com/17363750/49433727-f1eed280-f7b2-11e8-8c3a-a3131af63a5c.png)

### Create the index pattern for users

(here you can choose between `join_date`, `join_datetime` and `join_time`, I suggest you to choose `join_date` but feel free to use what is best for your use case)

![immagine](https://user-images.githubusercontent.com/17363750/49433901-5316a600-f7b3-11e8-8a06-f39a6e989d4e.png)

### FAQ

Q: But I **do not** see that Twint created and index: `[+] Index "twintuser" created!` and/or `[+] Index "twinttweets" created!` are **not** printed, why?

A: Yesterday I pushed a fix, in order to have the correct type fields so you have to update your local repo/package as well.

Run `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint` to update your local package

**Comment by murchie85** [comment]
Hi guys, when i try to run the twint as shown in the instructions I get bad request 400, any ideas? 

![image](https://user-images.githubusercontent.com/23745313/60214132-d0435e80-985c-11e9-8c40-958cfb9e94f7.png)

**Comment by pielco11** [comment]
Are you using ELK 6 or ELK 7?

Elastic removed types from ELK 7, that's the issue. If you are still using ELK 6, there is an issue (closed) about this. I highly suggest to you upgrade to ELK 7 (no data will be lost, steps to follow quite easy)

-------- Messaggio originale --------
On 26 Giu 2019, 22:53, Adam McMurchie < notifications@github.com> ha scritto:
Hi guys, when i try to run the twint as shown in the instructions I get bad request 400, any ideas?
￼
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.￼
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[https://github.com](<a href=)/twintproject/twint/issues/150?email_source=notifications">https://github.com/twintproject/twint/issues/150?email_source=notifications\u0026email_token=AEEPGJQUKO53SKEKSN5ZZOTP4PJMTA5CNFSM4FEG2WD2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYUZAOA#issuecomment-506040376", "url": "[https://github.com](<a href=)/twintproject/twint/issues/150?email_source=notifications">https://github.com/twintproject/twint/issues/150?email_source=notifications\u0026email_token=AEEPGJQUKO53SKEKSN5ZZOTP4PJMTA5CNFSM4FEG2WD2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYUZAOA#issuecomment-506040376", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by murchie85** [comment]
Hi, wow thanks for the quick reply! I have been working days to get this working. I am running elastic and kibana in containers (due to mac limits), so ES Ver 7 doesn't spin up I am afraid :( Is there a way to ignore the type?

**Comment by murchie85** [comment]
Thanks you, that fixed the issue!
