### ISSUE TITLE
[QUESTION] Getting profile information from list of users in userlist file?

### ISSUE THREAD

**Issue by hudmb** [twintproject/twint#183]
Is it possible to use the userlist command to get only the profile information from a list of Twitter handles in the userlist file? E.g. the userlist file contains: -

realdonaldtrump
stephenfry
johndoe
janedoe
...etc

Running Twint would produce a csv output with profile details for each user?

I'm sure it's possible, but can't figure out how to do it.

Thanks!

**Comment by pielco11** [comment]
#123 this feature is not ready yet, I'm closing this since is duplicate

**Comment by pielco11** [comment]
The only difference between this question and the one in issue n°123 is that here you specify that you would like (as me and others, I suppose) to specify a user-list and not just a single user, but I do think that the concept does not change

When issue 123 will be close this feature will be integrated since is interesting and time saving
