### ISSUE TITLE
[Question] Ability to extract followers with a minimal follower count

### ISSUE THREAD

**Issue by SundareshPrasanna** [twintproject/twint#193]
Is it possible to extract follower count from a twitter handle satisfying a condition?

**for example:** extract all followers of Elon Musk with their follower count > 10000

**Comment by pielco11** [comment]
Yes, it's possible and this can (actually could) be done in an easy way using `followers_object` which is a list containing every extracted follower... but this feature **is not** ready, yet, it's in development 

Another easy way is dumping followers to a json file, that load the json file itself, and elaborate the data with `for` loops and `if` statements

Another way, but not easy since you have to edit some code, is to add `if` statements while dumping followers

While `followers_object` is not ready to use, I suggest you the "json way" (you may also use the database or csv)

**Comment by SundareshPrasanna** [comment]
Thanks for the elaborate answer @pielco11 . What i'm trying to do is reduce the code running time by filtering only certain users with a filter on the followers count. The ideal situation as you also mentioned would be to somehow filter the users at the query level itself. Also similar to #171 is it possible to parallelize the extraction of followers ?

**Comment by pielco11** [comment]
@SundareshPrasanna I don't think that could be possible to parallelize the extraction of followers since it's a "serial process", one follower after another... but we can check it better if we can apply some improvements

Parallelizing queries it's on the way, now as now I cannot say when this feature will be available, we are working to make it asap
