### ISSUE TITLE
[request] how to get the coordinate of each Tweet? Not the geo location with radius.

### ISSUE THREAD

**Issue by skywalkerzhai** [twintproject/twint#202]

**Comment by pielco11** [comment]
Simply put: you can't, no more
#56

**Comment by skywalkerzhai** [comment]
Hey, Sorry, I am a beginner in the Github.
I do not know the rules. I noticed the issue 15 also only has one sentence.
I am just curious about this question and i do not know how to describe the question techically as you required. 
I feel it is just rude if you guys just close it and reply with 'you can't, no more'.
Thanks

**Comment by pielco11** [comment]
Hi @skywalkerzhai,

technically speaking your question is complete since is clear that you want the geo coordinates stored in the tweet. 

In the issue template are stored all the basic rules that one (me, you, everyone) should follow, I'm kindly asking you to pay close attention at this sentence:

> I have searched the issues and there are no duplicates of this issue/question/request

So using `is:issue geolocation` as search keywords will point you out one single closed issue, n° 56, since the reference `#56`, this means that this issue (202) and that issue (56) are strictly (more or less, it depends) related.

I'm sorry that you feel this behavior rude, I thought that giving you a short answer and a reference to an issue, with more details and a complete answer, was enough. 

Kindly,
Francesco

**Comment by pielco11** [comment]
For possible future situations, I suggest you to ask for details (as you rightly did here) about the reason of a specific behavior, like why we closed that issue and/or why that label was given, and so I'm asking you to check for duplicates and follow the instructions in the template in all its essence

For every question or clarification we are here, no one will ban you
