### ISSUE TITLE
[REQUEST] Provide a twitter json compatible

### ISSUE THREAD

**Issue by advancedlogic** [twintproject/twint#292]
Could you provide a way to export data in twitter json format like this (of course filling just the available fields):

[http://socialmedia-class.org/assets/img/raffi-krikorian-map-of-a-tweet.png](url)

**Comment by pielco11** [comment]
```python
import twint

c = twint.Config()

# Customize the fields to save
c.Custom["tweet"] = ["id", "tweet", "created_at", "conversation_id", "user_id", "username", "place"]
c.Store_json = True
c.Store_object = True
c.Search = "security"

twint.run.Search(c)

# for every tweet extract user's infos
tweets = twint.output.tweets_object
for t in tweets:
  c = twint.Config()
  c.Store_json = True
  c.Store_object = True
  c.Username = t.username
  twint.run.Lookup(c)
user_info = twint.output.users_object

# some code to reconstruct the given template
```

The only difference between the template you provided and Twint's template, is that the first has 2 nested object, user and place.

It's quite easy to reconstruct the given template, just iterate over one of the two objects (it dosen't matter which one since they have the same length) and create the hash-table. In the example I already specified the tweet's fields that you need, for the user you need every field and those are:
```python
fieldnames = [
            "id",
            "name",
            "username",
            "bio",
            "location",
            "url",
            "join_date",
            "join_time",
            "tweets",
            "following",
            "followers",
            "likes",
            "media",
            "private",
            "verified",
            "avatar",
            "background_image"
            ]
```
So, for example, to access to the username filed of the first scraped user do: `user_info[0].username`

**Comment by advancedlogic** [comment]
thanks
