### ISSUE TITLE
Timedelta not working

### ISSUE THREAD

**Issue by ShockGraphics** [twintproject/twint#323]
I use Python 3.6 and already updated twint.

### Description of Issue
If I am not mistaken,
c.Timedelta = 100`
is supposed to make a interval of 100 days for every request.
However, doing so makes no difference no matter which number I use.
There is always no interval at all.
I want to scrape 10000 tweets from 2006 until 2018. At the moment it only scrapes the most recent tweets. What do I have to do? 

### Environment Details
Windows 10 64 Bit 
Python 3.6
IDE: Pycharm

**Comment by pielco11** [comment]
Actually Twitter returns 20 tweets for every request, so if the last tweet (of that request) was tweeted two years before the first tweet (of that request) the "timedelta" is about 730 days.

`Timedelta` is used when the difference between `c.Since` and `c.Until` is too much, ref https://github.com/twintproject/twint/issues/102#issuecomment-391263217
