### ISSUE TITLE
Source of data in elasticsearch?

### ISSUE THREAD

**Issue by rgrunbla** [twintproject/twint#365]
Hi.
Using twint and the elasticsearch backend, is there a way to know from "where" do an item comes from?

I run the tool with multiple scraping options like --favorites, --full-profile, and so on, and I find data in elasticsearch that is hardly related to anyone: sometimes it's easy, it's written in the "mentions", or it is done by the account that I scrap. But sometimes it's not (I believe it's when I'm crawling favorites and retweets): is there a way to mark a tweet as originating from someone (or at least, mark the name of the person favoriting or retweeting the tweet inside the object) ?

**Comment by pielco11** [comment]
Hi @rgrunbla,

to accomplish this need I added `config.Essid`, which stands for "ElasticSearch Session ID". By the way, this is a `keyword` entity so it's almost like a text but with a few differences (you can't do full text search on this field, and you should do not need to)

So in your case I would specify something like `config.Essid= "likes_of_username"`. Then, when you will have to graph data in charts and stuff, you will have just to apply a filter with `essid: "likes_of_username"`. You would have to apply this filter either "locally" (for the single chart) or "globally" (for the whole dashboard), so choose wisely where to place the filter.

If you have another idea or suggestions, just feel free to let me know!

**Comment by rgrunbla** [comment]
Ok, so this is to be done before scraping data, right? Can I pass it on the commandline? Thanks!

**Comment by rgrunbla** [comment]
Ok, thanks, this is perfect (and available on the cli as --essid, for anyone reading this).
I guess, by default, one could generate some random hash (or some datestring) to avoid people (like me) discovering this after crawling 500k tweets !

**Comment by pielco11** [comment]
That's correct, you have to specify this field before scraping data. Technically you can update your already indexed tweets, but this is going to be a bit complicated since you have first get the tweets, update them specifying `essid` and then re-index them

About random hash, may you give me an example?

**Comment by rgrunbla** [comment]
Something like this:

```
if args.essid == "":
    time_string = time.strftime("%Y%m%d-%H%M%S")
    random_string = "''.join(random.choice(string.ascii_letters) for m in xrange(5))
    c.Essid = "%s_%s" % (time_string, random_string)

else:
    c.Essid = args.essid or 
```

Basically, have a way to distinguish each dataset "by default" (and the datetime is a nice touch).
What could also be done is just to put the username in there, or the args.userlist.

**Comment by pielco11** [comment]
Users can specify `config.Index_tweets` if they want differentiate the datasets strictly. This solution is better than specifying `config.Essid` since the data will be stored in a different index making the machine faster, the search for tweets faster and every interaction with the data, faster.

So for now I suggest to differentiate datasets with `Index_tweets` and subsets with `Essid`.
