### ISSUE TITLE
Better explanation of the csv module & fix broken examples 

### ISSUE THREAD

**Issue by NewCTwo** [twintproject/twint#366]
### Initial Check

- [X] Python version is 3.6;
- [X] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- X[] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran

```
import twint
import sys


twitter_username = sys.argv[1]

c = twint.Config()

c.Username = twitter_username
c.Custom["tweet"] = ["id"]["created_at"]["date"]["time"]["timezone"]["username"]["place"]["tweet"]["urls"]["photos"]["location"]["hashtags"]["link"]["video"]
c.Custom["user"] = ["bio"]
c.Store_csv = True
c.Output = str(twitter_username+"_folder")
c.Limit = 10

twint.run.Search(c)
```
### Error

```
me@me:~/Code$ time python3 testcsv.py nytimes
Traceback (most recent call last):
  File "makeCSV__00.py", line 10, in <module>
    c.Custom["tweet"] = ["id"]["created_at"]["date"]["time"]["timezone"]["username"]["place"]["tweet"]["urls"]["photos"]["location"]["hashtags"]["link"]["video"]
TypeError: list indices must be integers or slices, not str

real	0m0.349s
user	0m0.547s
sys	0m0.569s

```

### Description of Issue

I want to create a csv that looks exactly like I made it with the command line, but I keep getting empty files.
 
### EDIT

I changed my code based on this [this medium](https://medium.com/@adamstueckrath/social-media-data-science-and-an-international-crisis-f5463b803fca) but it still doesn't work the way I wanted:

```
c.Username = twitter_username
#c.Custom_csv = ["id", "created_at", "date", "time", "timezone", "username", "tweet", "urls", "photos", "location", "hashtags", "link", "video"]
c.Custom_csv = ["id", "created_at", "date", "time", "timezone", "username", "urls", "photos", "location", "hashtags", "link", "video"]
c.Custom["user"] = ["bio"]
c.Limit = 4
c.Store_csv = True
c.Output = str(twitter_username+"_folder")
``` 

It should only be collecting **four** tweets, but it gives me 20?

### Environment Details
Ubuntu 18.04

**Comment by pielco11** [comment]
`c.Custom['user']` is no more needed, I just updated the Wiki (this is not related to your issue)

According to the Wiki if you specify `c.Output = "something_folder"`, Twint will make the `something_folder` and save tweets into a file named `tweets.csv`, so the output file will be `something_folder/tweets.csv`. If you want to directly save into a specific file, just add `.csv` to the end. So something like `c.Output = "username_tweets.csv"`

You get 20 tweets because Twitter, for every request, returns 20 tweets

**Comment by NewCTwo** [comment]
I still can't customize the feilds. I'm running:

```
c.Username = twitter_username
c.Custom_csv = ["id", "username","tweet","photos"]
c.Limit = 2
c.Store_csv = True
c.Output = str(twitter_username+"_folder")
```

But the resulting csv still has all more than those 4.

**Comment by pielco11** [comment]
It's `config.Custom` not `config.Custom_csv`
-------- Messaggio originale --------
On 1 Mar 2019, 20:38, NewCTwo ha scritto:

**Comment by NewCTwo** [comment]
I tried both 
`c.Custom = ["id", "username","tweet","photos"]`
and 
`c.Custom["tweetstore"] = ["id", "username","tweet","photos"] `

Neither give me _only four_ fields.

**Comment by pielco11** [comment]
According to the Wiki, it's config.Custom['tweet'] = [...]

As said, you do not get only 4 tweets because Twitter returns 20 tweets per request
-------- Messaggio originale --------
On 1 Mar 2019, 21:34, NewCTwo ha scritto:

**Comment by NewCTwo** [comment]
I fixed it: the field isn't "video", it's "video_url". That should be updated.

**Comment by pielco11** [comment]
Honestly I do not find the `video_url` field

**Comment by pielco11** [comment]
https://github.com/twintproject/twint/blob/b5338e47a5ed55d001d6d48860cd249cadb0293e/twint/storage/write_meta.py#L1-L27

**Comment by pielco11** [comment]
If you look at these lines
https://github.com/twintproject/twint/blob/b5338e47a5ed55d001d6d48860cd249cadb0293e/twint/output.py#L66-L68

You see that `write.Csv` is called, which is this fuction
https://github.com/twintproject/twint/blob/b5338e47a5ed55d001d6d48860cd249cadb0293e/twint/storage/write.py#L49-L62

Then this function is called
https://github.com/twintproject/twint/blob/b5338e47a5ed55d001d6d48860cd249cadb0293e/twint/storage/write.py#L33-L43

Which then calls
https://github.com/twintproject/twint/blob/b5338e47a5ed55d001d6d48860cd249cadb0293e/twint/storage/write_meta.py#L107-L115

And since we are talking about tweets, it returns only the fields specified in `config.Custom` 
https://github.com/twintproject/twint/blob/b5338e47a5ed55d001d6d48860cd249cadb0293e/twint/storage/write.py#L35

**Comment by pielco11** [comment]
I guess that you are seeing deprecated fields

I kindly ask you to upgrade your Twint version with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`
