### ISSUE TITLE
[NEW FEATURE] Getting "Top" tweets not newest 

### ISSUE THREAD

**Issue by mariyamilosh** [twintproject/twint#371]
# Issue Template
Please use this template!

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
`twint -g="30.3255568815976,-81.7671865745302,0.578km" -o 'file.csv' --csv`

### Description of Issue
Geocode search often gives inconsistent results. For example, this line produces 5 tweets, but there are about 90 if I search the same query in Twitter [manually](https://twitter.com/search?q=geocode%3A30.3255568815976%2C-81.7671865745302%2C0.578km&src=typd&lang=en). Why could this happen?

### Environment Details
Mac OS Mojave. Running this in terminal.

**Comment by pielco11** [comment]
![immagine](https://user-images.githubusercontent.com/17363750/54084224-54b1b600-432e-11e9-8699-47204497ecf8.png)

Twint currently searches for `Latest` tweets and not for `Top`. If you switch to `Top` you get more tweets because "the algorithm of Twitter finds more tweets with that criteria".

Currently the "search for Top tweets" is not available

All the game resides here https://github.com/twintproject/twint/blob/d95dfdb5a034d83c2f7b7e6e2c4e7c7b215aec20/twint/url.py#L52-L63 and `params` needs to be changed accordingly

"Latest" url: `https://twitter.com/search?f=tweets&vertical=default&q=geocode%3A30.3255568815976%2C-81.7671865745302%2C0.578km&src=typd&lang=en`

"Top" url: `https://twitter.com/search?vertical=default&q=geocode%3A30.3255568815976%2C-81.7671865745302%2C0.578km&src=typd&lang=en`

So one has just to remove `('f', 'tweets'),`
I did not test this, yet, so the result could be quite unexpected

**Comment by mariyamilosh** [comment]
Removing this line did the trick, at least with my example. Thanks!

**Comment by pielco11** [comment]
I'll keep this open to remind me to add this feature (getting first "Top" tweets)

**Comment by pielco11** [comment]
#291

**Comment by pielco11** [comment]
## To get popular tweets
```python
import twint

c = twint.Config()
c.Username = "username"
c.Popular_tweets = True

twint.run.Search(c)
```

## To get latest tweets
By default `config.Popular_tweets = False`
```python
import twint

c = twint.Config()
c.Username = "username"
c.Limit = 20

twint.run.Search(c)
```

**Comment by AntonioNieto92** [comment]
Hello:

Could you please let me know how popular tweets work?. For example, I got some tweets with a few rts and likes (examples with 0 rts and 0 likes) so I thought that populars had many rts and likes in order to be that.

Thanks in advance!

**Comment by pielco11** [comment]
@AntonioNieto92 only Twitter knows who it actually works. There could be something in their docs

**Comment by AntonioNieto92** [comment]
> @AntonioNieto92 only Twitter knows who it actually works. There could be something in their docs

Get it!. FYI

**Why don't I see the Tweets I like in top Tweets?**
Top Tweets are the most relevant Tweets for your search. We determine relevance based on the popularity of a Tweet (e.g., when a lot of people are interacting with or sharing via Retweets and replies), the keywords it contains, and many other factors. If Tweets you love aren't showing up as top Tweets, it means they may not be the most relevant results for your search. You can tap Latest to see the most recently-posted Tweets matching your query.
