### ISSUE TITLE
Format is string for Date on elasticsearch

### ISSUE THREAD

**Issue by sebastienhouzet** [twintproject/twint#397]
Hello,

### Command Ran
twint -u noneprivacy -es elasticsearch:9200 --limit 10

### Description of Issue
Datas sending to elasticsearch have an error on date format.
It is string and not possible to change it.

### Environment Details
> Ubuntu 18.04

![Capture d’écran 2019-04-17 à 22 04 06](https://user-images.githubusercontent.com/2550639/56317434-08dc0300-615d-11e9-87d8-fc5164bd6585.png)

Normaly on your doc, you explain push date on this screen configuration.

![Capture d’écran 2019-04-17 à 22 05 47](https://user-images.githubusercontent.com/2550639/56317436-08dc0300-615d-11e9-8190-30c8032bcd5b.png)

**Comment by pielco11** [comment]
Are you sure to be using the latest version of Twint? If not, please update, then delete the old index (both the index and the pattern itself, you delete the first via `Dev Tools` and the second in `Management`) and retry. Otherwise you can just specify another index name with `--index-tweets`. Example: `twint -u user -es host:port -it my_custom_index` (`-it` is an alias for `--index-tweets`)

Twint automatically creates the index if it does not exist.

**Comment by sebastienhouzet** [comment]
I have install with this command : pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint

**Comment by pielco11** [comment]
Did you create the index first and than used Twint?

Twint creates the index if it does not exist, `[+] Index created` is shown in the output in such case

**Comment by sebastienhouzet** [comment]
Index is created by your script python.

**Comment by pielco11** [comment]
Since 7.0.0 Elasticsearch removed `types`, that's breaking the index creation and so it's not created an index as we want (with `date` as date and not string). I'm solving this issue right now

**Comment by pielco11** [comment]
@sebastienhouzet please delete the old index (in `Dev Tools`, `DELETE twinttweets`) and re-run Twint as usual

**Comment by sebastienhouzet** [comment]
It works :)

I can finish prepare a docker for twint :)
