### ISSUE TITLE
[REQUEST] add tweeters follower count and following count

### ISSUE THREAD

**Issue by aabid0193** [twintproject/twint#398]
Is it possible to add another column in the output to display the follower and following counts when using the search parameter?

**Comment by pielco11** [comment]
That could be possible. But you could just store the tweets in a list `config.Store_object = True`, then iterate over the tweets, filter the users while you iterate over the list (so that you do not have to fetch already fetched data), fetch the following and follower count with `twint.run.Lookup(c)`

There are some examples in the Wiki

[Get user info](https://github.com/twintproject/twint/wiki/Module#fetch-informations-from-a-users-profile)
[Store tweets in list](https://github.com/twintproject/twint/wiki/Module#save-data-tweets-users--in-lists-ram)

**Comment by aabid0193** [comment]
I tried to do this. I wasn't able to effectively iterate over the twint.tweet_objects to get the profile information for the list of users though. Possible to show me the way?

**Comment by aabid0193** [comment]
import twint
    for user in user_list:
        c = twint.Config()
        c.Username = user
        twint.run.Lookup(c)


Above is what I tried

**Comment by pielco11** [comment]
`twint.output.tweets_object` is not for users, is for tweets

In the examples is showed everything that you need
