### ISSUE TITLE
[Question] Search also retweets

### ISSUE THREAD

**Issue by dshahrokhian** [twintproject/twint#404]
### Command Ran
`twint -s <text>`

### Description of Issue
Unlike Twitter's Search API, the search feature in Twint does not provide retweets. Is there any way to get those via Search, or get all retweets of a given tweet id?

**Comment by pielco11** [comment]
Currently the "get retweets" feature is broken and needs to be fixed

**Comment by dshahrokhian** [comment]
How is it broken? You mean adding the `--retweets` parameter? As far as I am concerned Twint is using Search Operators, from which including retweets seems to not be an option. Am I wrong?

**Comment by pielco11** [comment]
Now you have to update Twint and you then you will be able to scrape the retweets

**Comment by dshahrokhian** [comment]
@pielco11 thank you for taking the time to look into this. It still does not seem to work for me though. Now the error is `root:twint.run:Twint:Feed:noDataExpecting value`, by using the following command:

`twint -s <text> --retweets`

**Comment by pielco11** [comment]
@dshahrokhian because you can't search for tweets

Try with something like `twint -u user --retweets`

```python
import twint

c = twint.Config()
c.Username = "user"
c.Retweets = True
twint.run.Profile(c)
```

`run.Profile` is required since Twint scrapes the user's timeline

**Comment by AntonioNieto92** [comment]
Hello:

with this:

>import twint

c = twint.Config()
c.Username = "RobertoEntio"
c.Store_json = True
c.Output = "tweets.json"
c.Since = "2019-04-01"
c.Until = "2019-04-05"
c.Retweets = True

twint.run.Profile(c)

It doesn't work and it starts to return tweets from now but not in the interval defined above

Is it a bug?
Thanks in advance.

**Comment by pielco11** [comment]
That's not a bug, `c.Until` and `c.Since` work *only* with `twint.run.Search`

`twint.run.Profile` scrapes the user's timeline

**Comment by AntonioNieto92** [comment]
> That's not a bug, `c.Until` and `c.Since` work _only_ with `twint.run.Search`
> 
> `twint.run.Profile` scrapes the user's timeline

Thanks Francesco ;)

Is it possible to search n tweets between Since and Until, but randomly?. I mean, if I want 1000 tweets that contain "bitcoin" word, I don't want first/last 1000 tweets in this interval (imagine interval from 2019-05-01 to 2019-05-08, that would be first 1000 tweets from 2019-05-01 00:00 to 2019-05-01 XX:XX) . Do you understand me? :(

**Comment by pielco11** [comment]
Just scrape `m` tweets, with `m > n`, and then pick up them randomly

**Comment by AntonioNieto92** [comment]
So would I have to get all the tweets between 2019-05-01 to 2019-05-03 and then choose randomly?. It would suppose to get a huge amount of data, wouldn't it?. I want something like an amount of 1000 tweets in the interval mentioned previously. It would be something like 200 tweets randomly on 2019-05-01 (nor first ones neither last ones) + 500 on 2019-05-02 (nor first ones neither last ones) + 300 on 2019-05-03 (nor first ones neither last ones). I think that I would have to get tweets in a especific day and then choose randomly between them. Could I put hours in Since and Until (I think it would be another option)?

**Comment by pielco11** [comment]
You can't put hours in Since and Until

All the tweets are given sequentially, so there's not why to ask for a random sorting
