### ISSUE TITLE
Unicode problem in Persian language

### ISSUE THREAD

**Issue by ha7283** [twintproject/twint#405]
### Command Ran
import twint
c = twint.Config()
c.Search = 'علی'
c.Since = "2019-04-28"
c.Until = "2019-04-29"
c.Store_csv = True
c.Output = "test01"
twint.run.Search(c)

### Description of Issue
I want to collect twits that has  "علی"  word (It is a Persian word). but twint also scrap Arabic word by shape of "علي".
"ی" is a persian  character by unicode U+06CC 
"ي" is an arabic  character by unicode U+064A
why twint search can't separate this two character?
thanks bro.
### Environment Details
>Using Windows 10 , Python 3.6

**Comment by pielco11** [comment]
I guess that this issue is on Twitter side. Twint simply read the input and ask for data to Twitter

I tested your query, and Twint is passing the correct character

![immagine](https://user-images.githubusercontent.com/17363750/57030564-68e6a500-6c45-11e9-8b03-a249ec08e49f.png)

I tested both words with my font, and the correct one is being passed

![immagine](https://user-images.githubusercontent.com/17363750/57030678-cb3fa580-6c45-11e9-8362-0d9548c6bd3e.png)
