### ISSUE TITLE
Place & Location column issue

### ISSUE THREAD

**Issue by 7walls** [twintproject/twint#448]
Hi, 

I've been using twint for 1 month for a research project and I'm interested in the tweet's geolocation during crisis situation. I'm running twint on a Mac OS 10.12.6.

Everything works perfectly so far (and by the way I really thank you for this project) but this week I'd run twint and the "place" and "location" columns always remain empty.

I double check with specifics tweets I spotted where the "location" column" weren't empty 2 weeks ago but today it's only returning empty .CSV cells.

Do you know what's happening ?

Thank you very much

**Comment by pielco11** [comment]
![image](https://user-images.githubusercontent.com/17363750/59145544-9ca3b000-89e5-11e9-8455-572f82a02cdb.png)
if you leave `c.Location = True` commented, you will not get the 'place' of the tweet, and neither the 'location' (which is about the user, and not the tweet)

![image](https://user-images.githubusercontent.com/17363750/59145598-77fc0800-89e6-11e9-895c-0cce11c5e3b3.png)

But if you comment out that statement, you will get both 'location' and 'place'

![image](https://user-images.githubusercontent.com/17363750/59145615-995cf400-89e6-11e9-981b-dc569be98878.png)

Honestly I did not cover the 'get location' feature, but I guess that I'll remove it since is pretty useless. It's about the user and not the tweet, since it should be available via `.Lookup` and not search

**Comment by pielco11** [comment]
I removed `Location` field. Now to get 'place` of the tweet you have still to specify `c.Location = True`:

```python
import twint

c = twint.Config()
c.Username = "target"
c.Location = True
c.Store_csv = True
c.Output = "backup.csv"

twint.run.Search(c)
```
