### ISSUE TITLE
how to update search results

### ISSUE THREAD

**Issue by jamestch** [twintproject/twint#457]
### Initial Check

>Make sure you've checked the following:

- [checked] Python version is 3.6.8;
- [checked] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [checked] I have searched the issues and there are no duplicates of this issue/question/request.

### python3 test.py

import twint

c = twint.Config()
c.Search = "basketball"
c.Resume = "history_ids.txt"
c.Store_json = True
c.Output = "basketball.json"
c.Lang = "en"
c.Count = True
twint.run.Search(c)

### Description of Issue
>I  want to use "config.Resume"  to update data in basketball.json if  there has new tweet in my search request when I run test.py every ten minutes. But it seem does not work, it start search from the last recent tweet.

### Environment Details

Package           Version  Location
----------------- -------- ---------------------------------------------
aiodns            2.0.0
aiohttp           3.5.4
aiohttp-socks     0.2.2
async-timeout     3.0.1
attrs             19.1.0
beautifulsoup4    4.7.1
cchardet          2.1.4
certifi           2019.3.9
cffi              1.12.3
chardet           3.0.4
elasticsearch     7.0.0
fake-useragent    0.1.11
geographiclib     1.49
geopy             1.19.0
idna              2.8
idna-ssl          1.1.0
multidict         4.5.2
numpy             1.16.3
oauthlib          3.0.1
pandas            0.24.2
pip               19.1
pycares           3.0.0
pycparser         2.19
PySocks           1.6.8
python-dateutil   2.8.0
pytz              2019.1
requests          2.22.0
requests-oauthlib 1.2.0
schedule          0.6.0
setuptools        41.0.1
six               1.12.0
soupsieve         1.9.1
tweepy            3.7.0
twint             1.2.3    /home/james/app/twitter_crawler/src/twint
typing            3.6.6
typing-extensions 3.7.2
urllib3           1.25.2
wheel             0.33.1
yarl              1.3.0

**Comment by pielco11** [comment]
`config.Resume` resumes the scrape from the latest scraped tweet, which turns out to be the oldest one since the scrape goes back in time

You could run a script that fetches bunches of tweets and that resumes if the id of the latest scraped tweet is higher than the one of the previous session

**Comment by elseeoh** [comment]
Having the same problem, is this usage correct? 

c = twintConfig()
c.Search = "example"
c.Store_csv = True 
c.Until = "2019-03-27"
c.Since = "2019-03-13"
c.Output = "example.csv"
twint.run.Search(c)

Twint crashes after 15 mins, I then run:

c = twint.Config()
c.Search = "example"
c.Resume = "example.csv"

However it does not continue from the oldest tweet, it reverts to the most recent

(Thanks for the great project!)

**Comment by pielco11** [comment]
c.Resume, resumes from a "resume file" not the output file

Please add c.Resume in your script, give it a custom name and then retry

-------- Messaggio originale --------
On 20 Giu 2019, 17:22, elseeoh < notifications@github.com> ha scritto:
Having the same problem, is this usage correct?
c = twintConfig()
c.Search = "example"
c.Store_csv = True
c.Until = "2019-03-27"
c.Since = "2019-03-13"
c.Output = "example.csv"
twint.run.Search(c)
Twint crashes after 15 mins, I then run:
c = twint.Config()
c.Search = "example"
c.Resume = "example.csv"
However it does not continue from the oldest tweet, it reverts to the most recent
(Thanks for the great project!)
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.￼
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[https://github.com](<a href=)/twintproject/twint/issues/457?email_source=notifications">https://github.com/twintproject/twint/issues/457?email_source=notifications\u0026email_token=AEEPGJQPE6O2OLZMFXHAVILP3OODVA5CNFSM4HZQV4C2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYFXYFQ#issuecomment-504069142", "url": "[https://github.com](<a href=)/twintproject/twint/issues/457?email_source=notifications">https://github.com/twintproject/twint/issues/457?email_source=notifications\u0026email_token=AEEPGJQPE6O2OLZMFXHAVILP3OODVA5CNFSM4HZQV4C2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYFXYFQ#issuecomment-504069142", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by jamestch** [comment]
I set config.Debug=True, and  I can get the "max_position=thGAVUV0VFVBaGgL35vo7Z2B8WgICh3fOT2dgfEjUAFQAlAFUAFQAA" of the most recent tweet from head of twint-request_urls.log. Then I write the max_position value to the history_ids.txt by hand. When run python3 again,  it start  from the most recent tweet as same as last time run.

**Comment by pielco11** [comment]
You are right

![immagine](https://user-images.githubusercontent.com/17363750/59918989-8b679400-9426-11e9-9624-1ab72f0c7620.png)

It seems that Twitter changed something else since the last fix (about 20 days ago). I'll dig deeper and try to provide a fix.

In the mean time you can "resume" with `since` and `until`. You'll have a lot of duplicates but, now as now, it's the only workaround I guess

**Comment by NightMachinary** [comment]
Isn’t it possible to add second granularity to ‘since’ and ‘until’? Btw, resume worked for me, but it just resumes a broken session, not updating the results with new tweets since the last scrape.

**Comment by NightMachinary** [comment]
Or better yet, why not add a ‘since-id’ to the search, with which it’d become trivial to update with new tweets?

**Comment by pielco11** [comment]
@NightMachinary good point! PR are open if you want to contribute!

**Comment by Rafia13** [comment]
import twint

# Configure
c = twint.Config()
c.Username = "now"
c.Search = "fruit"

# Run
twint.run.Search(c)

It doesnot show output , can anyone help me? i'm beginner

**Comment by pielco11** [comment]
@Rafia13 that account is suspended
