### ISSUE TITLE
[QUESTION] Sharp decline in the overall number of tweets in May 2015

### ISSUE THREAD

**Issue by LiviaToric** [twintproject/twint#475]
I'm trying to scrap all the tweets in a specific area from 2011 to 2019 and saw a drastic decline in the number of tweets in May 2015 (image attached)

<img width="624" alt="Screen Shot 2019-07-14 at 5 00 26 PM" src="https://user-images.githubusercontent.com/7495862/61189475-09047580-a65c-11e9-8719-3dc969254e2c.png">

Is this the norm for everyone? What happened in May 2015? Or is this a bug?

**Comment by pielco11** [comment]
Hi @LiviaToric 

without any further information I can only assume that everything is as expected, so no bugs and just a decline

**Comment by LiviaToric** [comment]
Hi @pielco11 
Thanks for getting back to me.

There is a problem I noticed, when I ran 
twint -g="41.795391,-71.390099,4.1km" --since 2014-08-22 --until 2014-08-24 
The run abruptly stops at 503102420311085057 2014-08-23 04:52:18 EDT. 
No tweets came after that time stamp.

Not sure what's happening. 
Please let me know, thanks!

**Comment by pielco11** [comment]
I tested your query and I can confirm that something is not working properly, I'm checking it out right now

Thank you for reporting

**Comment by pielco11** [comment]
At first glance it seems that Twint stops because Twitter does not return more data

![immagine](https://user-images.githubusercontent.com/17363750/61207283-ff7b1c00-a6f4-11e9-8a96-907aa09cce2e.png)

**Comment by pielco11** [comment]
## UPDATE

with this little script
```python
import twint

c = twint.Config()
c.Geo = "41.795391,-71.390099,4.1km"
c.Since = "2014-08-23"
c.Until = "2014-08-24"

twint.run.Search(c)
```
Twint stops at the tweet with id `503102420311085057`

![immagine](https://user-images.githubusercontent.com/17363750/61207950-9eecde80-a6f6-11e9-8abb-307158dda904.png)

But if change `since` and `until` params for the next date-window we get all the expected tweets
```python
import twint

c = twint.Config()
c.Geo = "41.795391,-71.390099,4.1km"
c.Since = "2014-08-22"
c.Until = "2014-08-23"

twint.run.Search(c)
```

### At the beginning

![immagine](https://user-images.githubusercontent.com/17363750/61208212-289cac00-a6f7-11e9-91dd-9daebcff818b.png)

### At the end

![immagine](https://user-images.githubusercontent.com/17363750/61208137-fee38500-a6f6-11e9-98a1-697107088d28.png)

(02:00 CEST = 00:00 UTC)

## Conclusions

I guess there's something wrong with Twitter. I guess you to use the official API to cover the 7h missing tweets

**Comment by LiviaToric** [comment]
Thanks! That makes sense, I'll try that.
