### ISSUE TITLE
[REQUEST] Update flag so I can append to the beginning of a csv that's already in progress.

### ISSUE THREAD

**Issue by NewCTwo** [twintproject/twint#478]
### Initial Check
- [X] Python version is 3.6;
- [X] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [ ] I have searched the issues and there are no duplicates of this issue/question/request. (Actually there were, but they were closed with no solution)

### Description of Issue
I started a csv scrape about 4 months ago. When I tried to run the program again, because of course they have tweeted hundreds of times since then, it just got even OLDER tweets from last year and added them to the end.

There's no way to add NEW tweets to the beginning of a csv that's already been created. `c.Resume` is for picking up where you left off and appending to the end (not the beginning), and 'c.Until' doesn't work because it's only specific to the day and since people can of course post multiple tweets per day I would either have overlap or miss a few.

### Solutions
Make `c.Until` specific down to the second (or even millisecond if possible.)
Create a in progress flag
Create a stopping at flag: It will scrape until it reaches that tweet and stop there.

### Example One

    import twint

    c = twint.Config()
    c.Username = "twitter"
    c.Store_csv = True
    c.Update = True            #See?
    c.InProgressCSV = "./Data/Twint/twitter.csv"

    twint.run.Search(c)

### Example Two

    import twint

    c = twint.Config()
    c.Username = "twitter"
    c.Store_csv = True
    c.Output = "update.csv"
    c.StopAt = 1104849491776233481 #Twitter ID
    twint.run.Search(c)

### Environment Details
Linux 18.04 & Python 3.6

**Comment by pielco11** [comment]
Hi @NewCTwo and thank you for writing me

I understand your issues and I'll write you how you can deal with them.

> Make c.Until specific down to the second (or even millisecond if possible.)

Unfortunately you can't set `c.Until` to second or milliseconds due to how Twitter Search works (this can be simply verified via its advanced search page).

>  Create a in progress flag

If I understood correctly your idea about "in process flag", this is already given by the fact that Twint checks if the file already exists or not. In such case, tweets will be appended to the end.

>  Create a stopping at flag: It will scrape until it reaches that tweet and stop there.

Stopping tweets scrape at a given ID would not be always suitable since tweets can be deleted, account suspended, account changed to private, and a few other reasons. I suggest you to stop at the same day of when the tweet was tweeted, do some post-processing filtering, and then save your data

> I want new tweets added to the beginning of the file and not the end

Again, some post-processing is needed. You would have to read the two files where you saved temporary the data, open a new one and writing the header first. Then iterating over the tweets, sorting them by ID and then writing them to the new file iterating over the sorted list.
