### ISSUE TITLE
twint.run.Profile(c) not returning results; twint 2.1.7

### ISSUE THREAD

**Issue by calebglawson** [twintproject/twint#565]
### Initial Check
- [] Python version is 3.6; **Am actually using 3.7**
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
c = twint.Config()
c.Username = "staff"
c.Output = "tweets.json"
twint.run.Profile(c)

### Description of Issue
When the above command is run, the script returns "[!] Twitter does not return more data, scrape stops here."

### Workaround
Downgraded my twint install to 2.1.6, and am able to fetch results again.

### Environment Details
Windows 10, Python 3.7, running from command line

**Comment by pielco11** [comment]
You have to add `c.Profile_full = True` since you want to specify that you want to get the timeline. `twint.run.Profile` can be used even to get some retweets, so you have to specify if you want to use that function for a mean or another.

https://github.com/twintproject/twint/wiki/Configuration#profile

Plus, that profile is not shadow-banned so I suggest you to use `twint.run.Search` function instead (it's faster)
