### ISSUE TITLE
scrap particular hashtag on basis of date

### ISSUE THREAD

**Issue by riishabhz** [twintproject/twint#597]
hello 
i have used this command:-  twint  -s pineapple --since 2019-12-05 -o file.csv --csv
but i am getting error like this:- 
   return datetime.datetime.strptime(date, "%Y-%m-%d").strftime('%s')
valueError: Invalid format string

what could be the possible solution ?

**Comment by pielco11** [comment]
I'm unable to replicate your issue, also your syntax seems to be correct

**Comment by riishabhz** [comment]
yes i know but its not working , can you check is it working on your script.

**Comment by pielco11** [comment]
![immagine](https://user-images.githubusercontent.com/17363750/70318978-17c11400-1819-11ea-9044-efab2c596e89.png)

I just changed the `since` field to get some results

**Comment by riishabhz** [comment]
nope not working in my case :(
![twint](https://user-images.githubusercontent.com/35364271/70320573-1a3c6180-184b-11ea-8893-e7be889b03b0.PNG)

**Comment by pielco11** [comment]
I guess there's an incompatibility issue with Windows then

**Comment by riishabhz** [comment]
How can it be fixed?

**Comment by pielco11** [comment]
As of now I suggest to not run on Windows

I've some ideas like raw text splitting

**Comment by riishabhz** [comment]
ok  , please update me when its fixed :)

**Comment by Ali-khavanin** [comment]
@pielco11 
That's exactly what i was referring to.
And if i may ask a question : 
   How can i use timeDelta instead of Since and Until.

Cause those 2 doesn't seem working 😕

**Comment by pielco11** [comment]
@Ali-khavanin I removed `timeDelta` from the code since it was causing various issues, I'll push a workaround for Windows users

**Comment by pielco11** [comment]
Not having a Windows machine is quite limiting me, so I kindly ask you to retry now (git clone or pip+git) and let me know if something has changed

**Comment by riishabhz** [comment]
hello 
i have cloned the project but still same result.
![twint](https://user-images.githubusercontent.com/35364271/70600340-78838e80-1c15-11ea-94b0-c27ee4f50193.PNG)

**Comment by Ali-khavanin** [comment]
> hello
> i have cloned the project but still same result.
> ![twint](https://user-images.githubusercontent.com/35364271/70600340-78838e80-1c15-11ea-94b0-c27ee4f50193.PNG)

hi there!
i don't exactly know why but if u use the same command on ubuntu it would work properly!
i tried it on a virtual box

**Comment by riishabhz** [comment]
> hello
> i have cloned the project but still same result.
> ![twint](https://user-images.githubusercontent.com/35364271/70600340-78838e80-1c15-11ea-94b0-c27ee4f50193.PNG)

ooh ok cool , will try on linux now, thanx for the information :)

**Comment by pielco11** [comment]
The issue is not fixed yet, I'll reopen this

**Comment by riishabhz** [comment]
> The issue is not fixed yet, I'll reopen this

my bad :p

**Comment by pielco11** [comment]
So, since Windows users are having issues while converting the formatted date to epoch, I removed the option to filter by hour. Now it should work as expected; an example for `since` and `until` is `2019-12-11`, for non-Windows users `2019-12-11 12:00:00` is possible. What I did should be considered a workaround a not a solution

**Comment by riishabhz** [comment]
> So, since Windows users are having issues while converting the formatted date to epoch, I removed the option to filter by hour. Now it should work as expected; an example for `since` and `until` is `2019-12-11`, for non-Windows users `2019-12-11 12:00:00` is possible. What I've done should be considered as a workaround and not a solution

so should i clone again?

**Comment by pielco11** [comment]
@riishabhz yes

**Comment by riishabhz** [comment]
i have done git clone ,still same results , not able to do

**Comment by pielco11** [comment]
@riishabhz may you post the error message please?

**Comment by riishabhz** [comment]
i sort it out , i dont know why it wasnt updating from git so i copy pasted your code in url.py file and now its working :) thanx a lot @pielco11

**Comment by pielco11** [comment]
#605

**Comment by dataslug1** [comment]
Hi,
I am having this same issue even with latest version, I am using windows PC.  
Is there maybe any workaround we can do by defining the dates using the DateTime module?
Thank you

Code and errors:

import twint
searchterm = 'Barcelona'
config = twint.Config()
config.Search = searchterm
config.Lang = "en"
config.Limit = 100
config.Since = "2019–3–24"
config.Until = "2019–3–25"
config.Store_csv = True
config.Output = searchterm+".csv"
twint.run.Search(config)

Traceback (most recent call last):
  File "D:\user\Documents\Twintproject\Working.py", line 13, in <module>
    twint.run.Search(config)
  File "D:\user\Documents\Twintproject\venv\lib\site-packages\twint\run.py", line 410, in Search
    run(config, callback)
  File "D:\user\Documents\Twintproject\venv\lib\site-packages\twint\run.py", line 329, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "D:\user\Documents\Twintproject\venv\lib\site-packages\twint\run.py", line 38, in __init__
    self.d = datelock.Set(self.config.Until, self.config.Since)
  File "D:\user\Documents\Twintproject\venv\lib\site-packages\twint\datelock.py", line 30, in Set
    d.until = datetime.datetime.strptime(convertToDateTime(Until), "%Y-%m-%d %H:%M:%S")
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2020–3–25 00:00:00' does not match format '%Y-%m-%d %H:%M:%S'

**Comment by minamotorin** [comment]
You should use `-` (hyphen-minus), not `–` (en-dash).
