### ISSUE TITLE
Can I get both username and id in a quick way?

### ISSUE THREAD

**Issue by edwardqianofficial** [twintproject/twint#613]
# Can I get both username and id in a quick way? 
Hi! I am trying to scrap some follower's information of an account. But i only need username and id. I tried to customize it and save the results into csv. However the csv only store the username.
When I tried set the user_full as true, the csv did save both username and id. But the speed is too slow.Do I have a quicker way if I only want to scrap username and id? If not, Can i scarp only id instead of username? 
<img width="1134" alt="Screen Shot 2019-12-19 at 17 08 39" src="https://user-images.githubusercontent.com/37559758/71160496-a2c2f500-2282-11ea-8795-707a69015912.png">

**Comment by pielco11** [comment]
It's not possible to get both `username` and `id` as fast as getting only the `username`s, not yet at least

PS: I think that the title is wrong and misleading

**Comment by edwardqianofficial** [comment]
So the only way to get username and id is to use 'user_full'? If yes, is it possible to get only id in a quicker way?

**Comment by pielco11** [comment]
The only way to get more information than just an username, is to use `user_full`.

The reason is that the `id` resides in the user's page. So for every user you have to fetch the corresponding page, and then extract the `id`.
On the other side, when you fetch the followers/following, you get them in bunches of 20 handles.

A faster way might just be running different scripts. For example if you want the ID of 100 users, just run 20 scripts with 5 handles each. That would totally speed-up the process. You could do this in like 5 lines of bash

**Comment by edwardqianofficial** [comment]
Thanks for your caring and quick response! But would these parallel processing get the same result?

**Comment by pielco11** [comment]
@edwardqianofficial sure, you are basically running the same script/requests
