### ISSUE TITLE
--since and --until not working together and not able to geolocation of scraped tweets 

### ISSUE THREAD

**Issue by kotenyo** [twintproject/twint#719]
(venv) Ko-MacBook-Pro:SmartCity ko$ twint -g -s "traffic" --near 'London' --since "2020-01-01 00:00:00" -o Londontraff2020.csv --csv
usage: python3 twint [options]
twint: error: argument -g/--geo: expected one argument
(venv) Ko-MacBook-Pro:SmartCity ko$

**Comment by arthtalati** [comment]
I think you can not use both together! You could use --since to get tweets for that year or --until to get tweets before the date you mention in descending order(by date). It would be interesting to know why would you need to use both of these commands together?

**Comment by kotenyo** [comment]
No problem I wanted to collect tweets for a specified period for analysis but I will just use  - - since, my major issue lies in collecting the tweets geolocations to create an interactive map, is there any possible way to do this?

**Comment by arthtalati** [comment]
maybe you could use --Location feature in your csv and use reverse geo coding to get (lat, long) coordinates.

**Comment by lotsoaxolotls** [comment]
I am trying to collect tweets for a given time period, searching by hashtag, but there's such a large volume of data that I want to gather the data week by week, then merge the data later.

I was hoping I could use --since and --until to do this.

Why can't they work together? I can specify both on Twitter's Advanced Search (in a browser), and it seems to work fine.

**Comment by Aaronzinhoo** [comment]
I use `--since` and `--until` for this exact purpose and they work together. What you need  to do is provide the `-g` geo argument with an input. It requires "lat,long,radius" as the input. An example would be: `--geo 35.1,-127.23,25mi`. You can use mi or km for the geo argument. I would use `geo` over `near` since you have more control over the area you search for.
