### ISSUE TITLE
Question: Is there a way to not show output in the console?

### ISSUE THREAD

**Issue by santoshbs** [twintproject/twint#814]
I just started using Twint and find it very useful and easy to use. I have a question. Is there any way to avoid writing the fetched tweets to console, while tweets are being saved in a csv file? More so, is there a way to only output select column (e.g., date) to the console while all columns are saved to the csv file?

Thank you!
sbs

**Comment by hatsune-miku** [comment]
## To hide console output but still writing csv:
```
# assume that c = twint.Config()

c.Hide_output = True

c.Store_csv = True
c.Output = 'output.csv'
```

## To hide log, add this before `twint.run.Search()`:
```
import logging

logging.basicConfig(level=logging.CRITICAL + 1)
```
Use the 'hide log' snippet cautiously since it disables ALL logs in your program, unless logging.basicConfig is called somewhere else and given a lower log level.

## To output only selected columns while writting all columns into csv:
```
c.Hide_output = False

c.Format = 'username: {username}, replies: {replies}, ...'

c.Store_csv = True
c.Output = 'output.csv'
```
To know the usage of c.Format, see: [format.py](https://github.com/twintproject/twint/blob/master/twint/format.py)

**Comment by santoshbs** [comment]
@hatsune-miku, Thanks a ton! This works perfectly.
