### ISSUE TITLE
Is there any way to scrape more tweet?

### ISSUE THREAD

**Issue by yangyangdotcom** [twintproject/twint#962]
### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.8;
- [] Updated Twint with `pip3 install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
twint --search "black army matters" --stats -o file.csv --csv --since 2020-06-01 --until 2020-06-30 --lang en

### Description of Issue
>It only gave me about 50 tweets but I believe there are more!

### Environment Details
>I am using Windows 10 and I am running this in Anaconda

**Comment by himanshudabas** [comment]
I request you to please do a quick search of your queries on _Twitter Advanced Search_ and compare the results. That will save you a lot of time.
I did the [search](https://twitter.com/search?q=black%20army%20matters%20until%3A2020-06-30%20since%3A2020-06-01&src=typed_query&f=live) of your query and there were approx 50 tweets. and I was also getting approximately 50 tweets on _twint_ too.

Yes this number might be a bit different for you because _there is a timezone bug in twint right now_ for which I'll create a separate issue, but this bug can only affect the edges of the search date.
So if you are searching for the range of `2020-06-01` to `2020-06-30` you might not get some of the tweets which are tweeted on either 01-June or 30-June, but between theses two dates you'll get the complete tweet data.

**Comment by HegdeChaitra** [comment]
> ### Initial Check
> > If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.
> 
> > Make sure you've checked the following:
> 
> * [] Python version is 3.8;
> * [] Updated Twint with `pip3 install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
> * [] I have searched the issues and there are no duplicates of this issue/question/request.
> 
> ### Command Ran
> twint --search "black army matters" --stats -o file.csv --csv --since 2020-06-01 --until 2020-06-30 --lang en
> 
> ### Description of Issue
> > It only gave me about 50 tweets but I believe there are more!
> 
> ### Environment Details
> > I am using Windows 10 and I am running this in Anaconda

Temporary fix to the problem can be found here : #941 .
Twint needs to be installed as shown in #917 using `pip3 install --user --upgrade git+https://github.com/yunusemrecatalcam/twint.git@twitter_legacy2` .
